version: "3.8"

services:
  expressjs-app:
    build: .
    image: expressjs-app
    restart: always
    env_file:
      - .docker/app.env
    ports:
      - '4000:4000'
    command: npm run dev
    depends_on:
      - localstack
    volumes:
      - ./:/usr/src/expressjs-app/
      - /usr/src/expressjs-app/node_modules/
    networks:
      - node-network

  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_test}"
    image: localstack/localstack
    env_file:
      - .docker/localstack.env
    ports:
      - "4566:4566"            # LocalStack Gateway
      - "4510-4559:4510-4559"  # external services port range
    volumes:
      - "./.docker/localstack:/docker-entrypoint-initaws.d"
      - "${LOCALSTACK_VOLUME_DIR:-./.docker/volume}:/var/lib/localstack"
    environment:
      - SERVICES=sns,s3,dynamodb,ec2,sqs,config,appconfig
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY}
      - DEBUG=${DEBUG-}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      - LAMBDA_REMOTE_DOCKER=0
      - DOCKER_HOST=unix:///var/run/docker.sock
      - START_WEB=1
      - EXTRA_CORS_ALLOWED_HEADERS=Content-Disposition, Content-Type, x-amz-acl
      - EXTRA_CORS_EXPOSE_HEADERS=ETag
      - HOSTNAME_EXTERNAL=localstack
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
