service: aws-serverless-appconfig

custom:
  # Our stage is based on what is passed in when running serverless
  # commands. Or falls back to what we have set in the provider section.
  stage: ${opt:stage, 'offline'}
  region: ${opt:region, 'ap-northeast-2'}
  serverless-offline:
    host: "0.0.0.0"
    httpPort: 4000
    noPrependStageInUrl: true
    reloadHandler: true
  localstack:
    stages:
      # list of stages for which the plugin should be enabled
      - local
      - offline
    host: http://localhost # optional - LocalStack host to connect to
    edgePort: 4566 # optional - LocalStack edge port to connect to
    networks: # optional - attaches the list of networks to the localstack docker container after startup
      - node-network
    lambda:
      # Enable this flag to improve performance
      mountCode: True

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'local'}
  region: ap-northeast-2
  memorySize: 512
  timeout: 10
  logRetentionInDays: 90
  logs:
    httpApi: true
  httpApi:
    # metrics: true # Enable if you need
    cors: true

functions:
  app:
    handler: src/handler.handler
    # reservedConcurrency: 100
    events:
      - httpApi:
          path: "/{proxy+}"
          method: "*"

package:
  individually: true

plugins:
  - serverless-dotenv-plugin
  - serverless-bundle
  - serverless-localstack
  - serverless-offline
